apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-remote
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NotAnAddictz/manifests
    targetRevision: main
    path: cloudflare-tunnel-remote
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
